using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace UniSphere.Infrastructure.Migrations
{
    /// <inheritdoc />
    public partial class SyncCurrentModelForVpsStartup : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            // Forward-only compatibility migration.
            // Previous VPS-safe raw SQL migrations updated the database, but the EF
            // snapshot still described the old model. That makes Database.Migrate()
            // fail with PendingModelChangesWarning during API startup. Keep this
            // migration non-destructive and idempotent.
            migrationBuilder.Sql(@"
                ALTER TABLE ""Events"" ADD COLUMN IF NOT EXISTS ""Name"" text NOT NULL DEFAULT '';
                ALTER TABLE ""Events"" ADD COLUMN IF NOT EXISTS ""MaxParticipants"" integer NOT NULL DEFAULT 0;
                ALTER TABLE ""Events"" ADD COLUMN IF NOT EXISTS ""Date"" text NOT NULL DEFAULT '';
                ALTER TABLE ""Events"" ADD COLUMN IF NOT EXISTS ""Time"" text NOT NULL DEFAULT '';
                ALTER TABLE ""Events"" ADD COLUMN IF NOT EXISTS ""PosterUrl"" text NOT NULL DEFAULT '';
                ALTER TABLE ""Events"" ADD COLUMN IF NOT EXISTS ""Category"" text NOT NULL DEFAULT '';

                DO $$
                BEGIN
                    IF EXISTS (
                        SELECT 1 FROM information_schema.columns
                        WHERE table_name = 'Events' AND column_name = 'Title'
                    ) THEN
                        UPDATE ""Events""
                        SET ""Name"" = COALESCE(NULLIF(""Name"", ''), ""Title"");
                    END IF;

                    IF EXISTS (
                        SELECT 1 FROM information_schema.columns
                        WHERE table_name = 'Events' AND column_name = 'Capacity'
                    ) THEN
                        UPDATE ""Events""
                        SET ""MaxParticipants"" = CASE
                            WHEN ""MaxParticipants"" = 0 THEN ""Capacity""
                            ELSE ""MaxParticipants""
                        END;
                    END IF;

                    IF EXISTS (
                        SELECT 1 FROM information_schema.columns
                        WHERE table_name = 'Events' AND column_name = 'EventDate'
                    ) THEN
                        UPDATE ""Events""
                        SET ""Date"" = COALESCE(NULLIF(""Date"", ''), to_char(""EventDate"", 'YYYY-MM-DD')),
                            ""Time"" = COALESCE(NULLIF(""Time"", ''), to_char(""EventDate"", 'HH24:MI'));
                    END IF;

                    IF EXISTS (
                        SELECT 1 FROM information_schema.columns
                        WHERE table_name = 'Events' AND column_name = 'PosterImagePath'
                    ) THEN
                        UPDATE ""Events""
                        SET ""PosterUrl"" = COALESCE(NULLIF(""PosterUrl"", ''), ""PosterImagePath"");
                    END IF;
                END
                $$;

                CREATE TABLE IF NOT EXISTS ""ClubMemberships"" (
                    ""Id"" integer GENERATED BY DEFAULT AS IDENTITY,
                    ""UserId"" integer NOT NULL,
                    ""ClubId"" integer NOT NULL,
                    ""Status"" text NOT NULL DEFAULT 'Active',
                    ""CreatedAt"" timestamp with time zone NOT NULL DEFAULT now(),
                    CONSTRAINT ""PK_ClubMemberships"" PRIMARY KEY (""Id""),
                    CONSTRAINT ""FK_ClubMemberships_Clubs_ClubId"" FOREIGN KEY (""ClubId"") REFERENCES ""Clubs"" (""Id"") ON DELETE CASCADE,
                    CONSTRAINT ""FK_ClubMemberships_Users_UserId"" FOREIGN KEY (""UserId"") REFERENCES ""Users"" (""Id"") ON DELETE CASCADE
                );

                CREATE UNIQUE INDEX IF NOT EXISTS ""IX_ClubMemberships_UserId_ClubId""
                    ON ""ClubMemberships"" (""UserId"", ""ClubId"");
                CREATE INDEX IF NOT EXISTS ""IX_ClubMemberships_UserId""
                    ON ""ClubMemberships"" (""UserId"");
                CREATE INDEX IF NOT EXISTS ""IX_ClubMemberships_ClubId""
                    ON ""ClubMemberships"" (""ClubId"");
                CREATE INDEX IF NOT EXISTS ""IX_ClubMemberships_Status""
                    ON ""ClubMemberships"" (""Status"");

                ALTER TABLE ""Clubs"" ADD COLUMN IF NOT EXISTS ""Logo"" text NOT NULL DEFAULT '';
                ALTER TABLE ""Clubs"" ADD COLUMN IF NOT EXISTS ""ShortDescription"" text NOT NULL DEFAULT '';
                ALTER TABLE ""Clubs"" ADD COLUMN IF NOT EXISTS ""AboutText"" text NOT NULL DEFAULT '';
                ALTER TABLE ""Clubs"" ADD COLUMN IF NOT EXISTS ""FoundedYear"" integer NULL;
                ALTER TABLE ""Clubs"" ADD COLUMN IF NOT EXISTS ""ContactEmail"" text NOT NULL DEFAULT '';
                ALTER TABLE ""Clubs"" ADD COLUMN IF NOT EXISTS ""SocialLinks"" text NOT NULL DEFAULT '';
                ALTER TABLE ""Clubs"" ADD COLUMN IF NOT EXISTS ""Website"" text NOT NULL DEFAULT '';

                ALTER TABLE ""Notifications"" ADD COLUMN IF NOT EXISTS ""Type"" text NOT NULL DEFAULT '';
                CREATE INDEX IF NOT EXISTS ""IX_Notifications_Type""
                    ON ""Notifications"" (""Type"");
            ");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            // No-op: this migration is a forward-only compatibility/snapshot sync.
        }
    }
}
