using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace UniSphere.Infrastructure.Migrations
{
    /// <inheritdoc />
    [Migration("20260421193000_AddPhase3MembershipDiscoverySupport")]
    public partial class AddPhase3MembershipDiscoverySupport : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            // 3. Faz: Topluluk üyeliği tablosu ve discovery/vitrin kolonları güvenli şekilde eklenir.
            migrationBuilder.Sql(@"
                CREATE TABLE IF NOT EXISTS ""ClubMemberships"" (
                    ""Id"" integer GENERATED BY DEFAULT AS IDENTITY,
                    ""UserId"" integer NOT NULL,
                    ""ClubId"" integer NOT NULL,
                    ""Status"" text NOT NULL DEFAULT 'Active',
                    ""CreatedAt"" timestamp with time zone NOT NULL DEFAULT now(),
                    CONSTRAINT ""PK_ClubMemberships"" PRIMARY KEY (""Id""),
                    CONSTRAINT ""FK_ClubMemberships_Users_UserId"" FOREIGN KEY (""UserId"") REFERENCES ""Users"" (""Id"") ON DELETE CASCADE,
                    CONSTRAINT ""FK_ClubMemberships_Clubs_ClubId"" FOREIGN KEY (""ClubId"") REFERENCES ""Clubs"" (""Id"") ON DELETE CASCADE
                );

                CREATE UNIQUE INDEX IF NOT EXISTS ""IX_ClubMemberships_UserId_ClubId""
                    ON ""ClubMemberships"" (""UserId"", ""ClubId"");

                CREATE INDEX IF NOT EXISTS ""IX_ClubMemberships_UserId""
                    ON ""ClubMemberships"" (""UserId"");

                CREATE INDEX IF NOT EXISTS ""IX_ClubMemberships_ClubId""
                    ON ""ClubMemberships"" (""ClubId"");

                CREATE INDEX IF NOT EXISTS ""IX_ClubMemberships_Status""
                    ON ""ClubMemberships"" (""Status"");

                ALTER TABLE ""Clubs"" ADD COLUMN IF NOT EXISTS ""Logo"" text NOT NULL DEFAULT '';
                ALTER TABLE ""Clubs"" ADD COLUMN IF NOT EXISTS ""ShortDescription"" text NOT NULL DEFAULT '';
                ALTER TABLE ""Clubs"" ADD COLUMN IF NOT EXISTS ""AboutText"" text NOT NULL DEFAULT '';
                ALTER TABLE ""Clubs"" ADD COLUMN IF NOT EXISTS ""FoundedYear"" integer NULL;
                ALTER TABLE ""Clubs"" ADD COLUMN IF NOT EXISTS ""ContactEmail"" text NOT NULL DEFAULT '';
                ALTER TABLE ""Clubs"" ADD COLUMN IF NOT EXISTS ""SocialLinks"" text NOT NULL DEFAULT '';
                ALTER TABLE ""Clubs"" ADD COLUMN IF NOT EXISTS ""Website"" text NOT NULL DEFAULT '';

                ALTER TABLE ""Notifications"" ADD COLUMN IF NOT EXISTS ""Type"" text NOT NULL DEFAULT '';
                CREATE INDEX IF NOT EXISTS ""IX_Notifications_Type""
                    ON ""Notifications"" (""Type"");
            ");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            // 3. Faz: Geri alma senaryosunda yeni keşif/üyelik alanlarını kaldırır.
            migrationBuilder.Sql(@"
                DROP INDEX IF EXISTS ""IX_Notifications_Type"";
                ALTER TABLE ""Notifications"" DROP COLUMN IF EXISTS ""Type"";

                ALTER TABLE ""Clubs"" DROP COLUMN IF EXISTS ""Website"";
                ALTER TABLE ""Clubs"" DROP COLUMN IF EXISTS ""SocialLinks"";
                ALTER TABLE ""Clubs"" DROP COLUMN IF EXISTS ""ContactEmail"";
                ALTER TABLE ""Clubs"" DROP COLUMN IF EXISTS ""FoundedYear"";
                ALTER TABLE ""Clubs"" DROP COLUMN IF EXISTS ""AboutText"";
                ALTER TABLE ""Clubs"" DROP COLUMN IF EXISTS ""ShortDescription"";
                ALTER TABLE ""Clubs"" DROP COLUMN IF EXISTS ""Logo"";

                DROP TABLE IF EXISTS ""ClubMemberships"";
            ");
        }
    }
}
